services:
  ros2:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      ssh:
        - default
    container_name: ros2-devcontainer
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../ros2_ws:/root/ros/workspace
    stdin_open: true
    tty: true
